### ISSUE TITLE
How to split the dataset?

### ISSUE THREAD

**Issue by wdhudiekou** [PRIS-CV/PCA-Net#1]
I can't run the code easily, how to split the dataset for bird, car, and aircraft? How to get the corresponding train.txt and test.txt?
Looking forward to your reply!

**Comment by TIan1874** [comment]
You can split the dataset according to the official training/test split. I have put the train.txt and test.txt in /data directory for your reference.

**Comment by TIan1874** [comment]
> I can't run the code easily, how to split the dataset for bird, car, and aircraft? How to get the corresponding train.txt and test.txt?
> Looking forward to your reply!

You can split the dataset according to the official training/test split. I have put the train.txt and test.txt in /data directory for your reference.
